### PR TITLE
Remove async.waterfall

### PR DESCRIPTION
**Pull request by pksunkara**
Using `async.waterfall` is blocking the event loop.

/cc @zdne @honzajavorek @Almad

### CODE REVIEW

**Comment by Almad** [comment]
@pksunkara @zdne I'd be interested in measurement behind this. 

`async.waterfall` is no different from any other function call (that, yes, is blocking by default). But if anything, and if you want to do cooperative multitasking, it should IMHO be easier to wrap waterfall in `process.nextTick` that allows other things in queue to be executed.

I am not disputing results of your investigation, but I am personally really curious to see how this change affected performance and whether async is really performance og.

**Comment by zdne** [comment]
@Almad interesting – with our limited knowledge of this I guess we haven't realized wrapping it in `nextTick` is the way to go. /cc @smizell

**Comment by smizell** [comment]
@Almad @zdne In playing around with this last night, something was really strange. I've used `async.waterfall` a lot and have never seen it.

This would not block the event loop.

```coffeescript
return callback()
```

But if replaced with this exact code, it would block until all calls were finished.

```coffeescript
async.waterfall [
  (next) -> next()
], -> callback()
```

If you then introduced another `async.waterfall` in the callback chain, it would block until almost all had been completed.

**Comment by smizell** [comment]
@Almad @zdne Additionally, in the above example that blocked, if I changed to `async.series`, it worked.

**Comment by honzajavorek** [comment]
Could this be related? https://github.com/caolan/async/issues/696 Just browsed through their issues, I did not look into its internals.

**Pull request merged**
